### ISSUE TITLE
Feature request: Firefox version

### ISSUE THREAD

**Issue by Kasijjuf** [jparise/chrome-utm-stripper#11]
I would like to have this functionality in Firefox as well.

**Comment by jparise** [comment]
I don't use Firefox so I'm afraid this isn't something that I plan on building. Someone else id welcome to give it a try.

Here's a Safari version, for example: https://github.com/grahams/safari-utm-stripper

**Comment by skiant** [comment]
Hi @jparise ! Sorry to bump this closed issue, but the Firefox WebExtension system means your [Chrome .crx seems to be working fine in recent versions of Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension). There's a list of possible incompatibilities but I couldn't find anything in your extension that would break in Firefox. I also tried a temporary installation, which seemed to function as expected.

If you felt like publishing this to the Firefox Addons website, it would be much appreciated.

**Comment by jparise** [comment]
Thanks @skiant! That's useful information. I've been using Firefox more often recently, so I'm a bit more motivated to give this a try. If it works as easily as you note, I'll probably just add some details to the README and point to the published Addon.

If not, I'll consider writing a bepoke Firefox version.
