### ISSUE TITLE
Feature request: Remove mc_cid

### ISSUE THREAD

**Issue by algustionesa** [jparise/chrome-utm-stripper#12]
It do well on stripping UTM tracking, but it leave the tracking from mailchimp, so the url is not clean. so please add capability to remove  the mc_cid tracking too

**Comment by jparise** [comment]
Could you share an example URL so I can check the specific case you have in mind?

**Comment by jparise** [comment]
Thanks for the suggestion! I've added code to strip both `mc_cid` and `mc_eid` query string parameters.
