### ISSUE TITLE
Feature Request: Edge Browser Port

### ISSUE THREAD

**Issue by grand-lotus-iroh** [jparise/chrome-utm-stripper#15]
Is something like that possible with minimal hours? How many hours you think it would take to port this to a side-loaded extension for Edge browser?

Love the addon

**Comment by jparise** [comment]
I'm not familiar with Edge's plugin architecture, so I'm afraid I can't really say.

I don't think it was very difficult for @grahams to write [the Safari version](https://github.com/grahams/safari-utm-stripper).
