### ISSUE TITLE
Feature Request: custom tokens

### ISSUE THREAD

**Issue by traderd65** [jparise/chrome-utm-stripper#16]
In addition to UTM_ tokens being automatically removed from the URL, add the option to specify custom tokens to remove, e.g. mkt_tok

**Comment by doggy8088** [comment]
I think custom tokens is a good idea.  There are some other marketing platform provided some custom tokens (Query String parameters).  It will be good if author can implement this as an extension options.  Thanks @jparise !

**Comment by davidjb** [comment]
This would be great to have; as a further example, GitHub has just recently started tracking clicks in their Issue Tracker emails by adding `email_source=notifications&email_token=[huge long token]` to the URLs.

**Comment by smed79** [comment]
@jparise Is something planning for what is requested here ?

**Comment by jparise** [comment]
I don’t currently have plans to build a configuration system.

**Comment by gitressa** [comment]
Custom tokens would be awesome. I am just now having issues with newsletter links using `ui` and `eType` tokens, which don't get removed.

The add-on works great for the already defined tokens, so thanks for making it!

**Comment by gitressa** [comment]
Two examples of the tokens mentioned above:

* https://example.org?eType=Email&eId=xyz
* https://example.org?ui=xyz_abc-def&sd=2002&cid_source=dnl&cid_medium=email&cid_content=art2HL&cid=22&mid=DM921222&rid=7435

**Comment by jparise** [comment]
[uBlock Origin](https://github.com/gorhill/uBlock) includes a [`removeparam`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam) feature that supports fine-grained matching and removal of query string parameters. That's a good alternative  for anyone who needs more customization than this extension currently provides.
