### ISSUE TITLE
Feature Request: on/off button and domain whitelist

### ISSUE THREAD

**Issue by siutsin** [jparise/chrome-utm-stripper#19]
It will be great if I can toggle to enable/disable the plugin for a specific site, something similar to the uBlock Origin.

![image](https://user-images.githubusercontent.com/904442/40953967-e335e8c4-68b4-11e8-8e44-f1dfb6d2774d.png)

**Comment by ivan** [comment]
I am not the author, but I am curious if there was some specific website that motivated this, where chrome-utm-stripper perhaps broke something?

**Comment by siutsin** [comment]
Can be two reasons:

1. My work is analytics related. But personally, I don't like the tracking stuff. So what I did at the moment is either open a new Chrome window with the guest account or disable the plugin temporarily.
2. (Just a guess) If a domain is whitelisted, can this be a workaround to use any other redirect plugins? Like the one stated in #13.

**Comment by jparise** [comment]
[uBlock Origin](https://github.com/gorhill/uBlock) includes a [`removeparam`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam) feature that supports fine-grained matching and removal of query string parameters. That's a good alternative  for anyone who needs more customization than this extension currently provides.
