### ISSUE TITLE
Feature request: Remove utm_referrer

### ISSUE THREAD

**Issue by mvalitov** [jparise/chrome-utm-stripper#23]
can utm_referrer be added to the list of deleted marks?

**Comment by jparise** [comment]
I've never seen this parameter used in the wild. Could you point me at an example?

**Comment by mvalitov** [comment]
for example, it is used in yandex.zen - https://hi-tech.mail.ru/review/xiaomi-mi-9-first-review-mi9-vs-huawei-mate-20-pro/?utm_referrer=https%3A%2F%2Fzen.yandex.com
