### ISSUE TITLE
Google Mail Outgoing Links Tracking

### ISSUE THREAD

**Issue by JimLoose** [jparise/chrome-utm-stripper#25]
Gmail modifies outgoing links to from https://meet.meetup.com to

https://www.google.com/url?q=https://meet.meetup.com/wf/click?upn%3DpEEcc32imY7Cq0tG1vgTt4flg9yZ8Zp-8Bo0KW6Np7p6kkxTKWTyKUlmrKK6T4NPuVZHos57bPQgJiogzoD-8GpKcg8B1PeStpre8IC9-8BxM7jYe-3D_oQYi-8Kjs0D-8KKGJhlKndrUbUoCcpCjqQCbeX5eReTzKStTGeOzqeitlxP8eBb3XX8D01Dqo9H3IunZ6OCBmgRKTBTGKczkUTCg3g4PD-8KeyWKj0Q8uZU1yheKlVEWh8KeBtcl6WeUKmLS5ulZ8EqCBUJyQvDdymBVy6joeOQehOHluo9eCKvjvVIen79eZTIjxdcqT5cbdd3Xzc93luRKYm8Q-3D-3D&source=gmeil&ust=1553648367113000&usg=eKWjKNEe7XKJ98xoogH3T4C33yHUB6eBTe

would be great to be cleaned! :)

**Comment by jparise** [comment]
This request falls more into the "domain-specific link rewriting" category and isn't something I want to support in this extension.

Fortunately, there are extensions like [Don't track me Google](https://chrome.google.com/webstore/detail/dont-track-me-google/gdbofhhdmcladcmmfjolgndfkpobecpg) that specialize in exactly this sort of thing.

**Comment by smed79** [comment]
try "Google search link fix" https://palant.de/2011/11/28/google-yandex-search-link-fix/
