### ISSUE TITLE
Account for empty tag values

### ISSUE THREAD

**Issue by joey04** [jparise/chrome-utm-stripper#26]
I recently had a case of `?utm_...&utm_term=&utm_...`

This empty `utm_term` tag was not stripped. (The others were normal tags, so they were stripped properly.)

I fixed it by changing the `+` at the end of the regex to `*`

(The full URL for this case is somewhat personal, so I won't share it here.)

**Comment by jparise** [comment]
Thanks for the report and the suggested fix, @joey04!
