### ISSUE TITLE
Feature Request: Forbes #tracker

### ISSUE THREAD

**Issue by foodfan** [jparise/chrome-utm-stripper#27]
Hi, Forbes.com adds a hashtag tracker at the end of its URL's. The link works fine without it. Would be great if you could remove those. Thanks!

**Comment by jparise** [comment]
I'm afraid I haven't figured out a reliable way to strip URI fragments from an extension so this isn't something I'm able to support at this time.

**Comment by jparise** [comment]
See also #10

**Comment by uBlock-user** [comment]
Why not just use [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) API ?

**Comment by jparise** [comment]
@uBlock-user I wasn't familiar with that API until you mentioned it. It looks like a nice improvement over regular expressions!

Does it handle fragments though? The documentation doesn't mention that, and I don't have time to experiment with it right now.

**Comment by uBlock-user** [comment]
@jparise I'm not sure what you mean by fragments.

**Comment by jparise** [comment]
@uBlock-user Fragment identifiers: https://en.wikipedia.org/wiki/Fragment_identifier

This is how Forbes is adding its tracker.

`URLSearchParams` would be an improvement over the current regular expression-based token stripping approach, but if it couldn't handle deleting the fragment identifier, then it couldn't be a drop-in replacement.

Separately, there is also the root issue noted in #10 where we can't match URLs with fragments without widening the rule to match all URLs, and I don't know how much of a performance regression that would cause.

**Comment by uBlock-user** [comment]
> URLSearchParams would be an improvement over the current regular expression-based token stripping approach, but if it couldn't handle deleting the fragment identifier, then it couldn't be a drop-in replacement.

It seems this API can't remove params starting with #, works with ? or &, not with # :(

Tested on youtube with the js below --

```
(function() {
		let query = '{{1}}';
		if (location.href.indexOf(query + '=') !== -1) {
			let url = new URL(location);
			url.searchParams.delete(query);
			window.location.href = url;
		}
})();
```
