### ISSUE TITLE
Feature Suggestion: Amazon Associates ID string

### ISSUE THREAD

**Issue by foodfan** [jparise/chrome-utm-stripper#28]
I have a plugin that adds my preferred amazon ID string to any amazon link so I can send commission to creators I like. This extension can easily replace that functionality with 2 benefits:
1) The Developers can leave their Amazon Associates ID as the default if users want to reward them for upkeep and hard work. (Or not change the default setting.)
2) Let users replace duplicate functionality in other plugins and customize that code for whoever they want to support.

Thanks

**Comment by jparise** [comment]
I think the features you suggest would be better in their own dedicated Amazon Associates extension. I'll keep this extension focused specifically on removing unwanted query string parameters.
