### ISSUE TITLE
[Request] Clean href links from UTM tracking codes

### ISSUE THREAD

**Issue by smed79** [jparise/chrome-utm-stripper#29]
Hey,

this is a feature request to clean the href links from UTM tracking codes

```
<a href="https://example.com/?utm_source=jparise&utm_medium=issue&utm_campaign=cleanhrefurls">....</a>
```

to become

```
<a href="https://example.com/">....</a>
```

in general what the user script [UTM-Remover](https://github.com/jparise/chrome-utm-stripper/files/3243631/UTM-Remover.user.js.txt) does.

Is it feasible?

**Comment by jparise** [comment]
This script doesn't touch the HTML content of the page. It instead filters out UTM (and other) query string parameters from the outgoing request.

**Comment by smed79** [comment]
Ok, thank you for taking the time to give me answers.
