### ISSUE TITLE
gmail - UTM query strings not stripped

### ISSUE THREAD

**Issue by smed79** [jparise/chrome-utm-stripper#30]
Hello,

example below link seems to be not managed by the extension, the `UTM` query strings are not stripped after you click the link.

html code

`<a href="https://play.google.com/store/apps/details?id=org.adblockplus.adblockplussbrowser&amp;referrer=utm_source%3Dblog%26utm_medium%3Demail%26utm_campaign%3Dabp_email" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://play.google.com/store/apps/details?id%3Dorg.adblockplus.adblockplussbrowser%26referrer%3Dutm_source%253Dblog%2526utm_medium%253Demail%2526utm_campaign%253Dabp_email&amp;source=gmail&amp;ust=1559510914545000&amp;usg=8tO8AFQjCNFAzxx1KMGRqYK2J3wVUJdb6A">https://play.google.com/store/<wbr>apps/details?id=org.<wbr>adblockplus.adblockplussbrowser&amp;<wbr>referrer=utm_source%3Dblog%<wbr>26utm_medium%3Demail%26utm_<wbr>campaign%3Dabp_email</a>`

email header

`<strong> Google Play:</strong> <a href=3D"https://play.google.com/store/app=
s/details?id=3Dorg.adblockplus.adblockplussbrowser&referrer=3Dutm_source%3Dblog%=
26utm_medium%3Demail%26utm_campaign%3Dabp_email">https://play.google.com/st=
ore/apps/details?id=3Dorg.adblockplus.adblockplussbrowser&referrer=3Dutm_source=
%3Dblog%26utm_medium%3Demail%26utm_campaign%3Dabp_email</a>
<BR><BR>`

Ss

![https://play.google.com/store/apps/details?id=org.adblockplus.adblockplussbrowser](https://imgur.com/VdFgyVT.png)

Thank you.

**Comment by jparise** [comment]
It looks like the UTM parameters are being passed as a set of encoding values within a `referrer` query string parameter.

We shouldn't strip to strip all parameters named `referrer`, and I don't feel good about adding logic that hunts within query string parameter values for things that look like UTM parameters, so I'm going to close this issue as "Won't Fix" unless someone can propose a nice alternate solution.

**Comment by smed79** [comment]
The good alternative is to implement the feature requested here https://github.com/jparise/chrome-utm-stripper/issues/16
