### ISSUE TITLE
Remove spm parameters as well

### ISSUE THREAD

**Issue by qwazix** [jparise/chrome-utm-stripper#42]
This url 
`https://www.aliexpress.com/item/4001103428101.html?spm=a2g0o.productlist.0.0.495138f1207jpB&algo_pvid=c9d31b36-30e7-4e56-b6d9-c91ec2ffe490&algo_expid=c9d31b36-30e7-4e56-b6d9-c91ec2ffe490-2&btsid=2100bdd716116038587508438ecf42&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_`

is equivalent to this

`https://www.aliexpress.com/item/4001103428101.html` 

I don't know if any other sites besides aliexpress use these tracking parameters but I'm just dropping this here in case you are interested.

**Comment by jparise** [comment]
I'm afraid these look a bit too generic to strip universally. If we had the ability to apply rules on a per-domain basis, I'd add this, but I don't think it's safe to add otherwise.
