### ISSUE TITLE
Remove stm parameter

### ISSUE THREAD

**Issue by orschiro** [jparise/chrome-utm-stripper#43]
Hi @jparise,

Thanks for your great extension!

Question: could it also remove stm parameters like below example?

https://app.sheetgo.com/workflows/1606149317012600L5SS/connections?stm_source=sheetgo-webapp-workflow-invite&stm_medium=email&stm_campaign=on-demand-invitation

**Comment by jparise** [comment]
Thanks for the suggestion. This has been added.

**Comment by orschiro** [comment]
That's great thanks!

Jon Parise ***@***.***> schrieb am Do., 18. März 2021, 22:22:
