### ISSUE TITLE
Did not work for the URL below

### ISSUE THREAD

**Issue by gersoncjunior** [jparise/chrome-utm-stripper#45]
Hi there,

Thank you for making such a great tool. I don't know why but for the url below it did not work.

https://vuejsdevelopers.com/2017/08/28/vue-js-ajax-recipes/?utm_source=linkedin-page-vjd&utm_medium=post&utm_campaign=var

**Comment by MordiSacks** [comment]
Works for me.

**Comment by ToadCast** [comment]
Works for me too. @gersoncjunior does it still happen to you? If not please close the issue, if yes then please provide a console log from the browser when you open the link to have more details.

**Comment by jparise** [comment]
I'm going to close this, but please reopen if new details become available.
