### ISSUE TITLE
Publish to Edge Add-ons

### ISSUE THREAD

**Issue by gabbsmo** [jparise/chrome-utm-stripper#47]
Microsoft Edge is compatible with Google Chrome extensions. While you can install from Chrome Web Store after opting in the experience for Edge users would be nicer if this extension was available from Edge Add-ons.

**Comment by jparise** [comment]
I don't use Microsoft Edge (or Windows), but it looks like it's available for non-Windows platforms. Have you already been able to verify that this add-on works as expected in Edge?

In general, this sounds useful to me, although it have to wait until I have a little time to familiarize myself with their developer registration and add-on publishing process.

**Comment by gabbsmo** [comment]
I have been using it for the last week and it seems to work as I expect.

**Comment by jparise** [comment]
The extension is now "In Review". I'll share an update once it's approved and published.

**Comment by DerekSeaman** [comment]
Would be great to see this in the Edge app extension store. Hopefully this can get bumped up.

**Comment by jparise** [comment]
I've made another submission attempt. We'll see how this one goes.

**Comment by jparise** [comment]
Now available from Edge Add-ons: https://microsoftedge.microsoft.com/addons/detail/mbhhijmdgnjdckplligicmjadcpndioj

**Comment by DerekSeaman** [comment]
Awesome thanks!
