### ISSUE TITLE
Could you add ?trackId

### ISSUE THREAD

**Issue by alaingraham13** [jparise/chrome-utm-stripper#48]
Netflix uses ?trackId=[....] to track links even when a do not track request is sent. It's likely used for advertising purposes as the site still functions without it (Screenshot 2). It is a capital I btw as seen in the screengrab (1) below.

Screengrab 1: ![image](https://user-images.githubusercontent.com/25529451/128121992-01457497-47ad-41d4-abe7-4b70f202ddf0.png)
Screenshot 2: ![image](https://user-images.githubusercontent.com/25529451/128122001-e162ebc8-90e6-46aa-8b0b-63dae1655afb.png)

**Comment by jparise** [comment]
I think this might be too general or ambiguous of a name to block without knowing more about its use. Otherwise, stripping it could brake interaction with some sites. (For example, this name could be use to select an audio track on some other site.)
