### ISSUE TITLE
Open to sharing the logic of this as a package?

### ISSUE THREAD

**Issue by chmac** [jparise/chrome-utm-stripper#49]
I'd love to see this kind of link stripping on more platforms, like a web site, a mobile app, and so on. There's a few plugins around, and each has a slightly different approach, different set of tracking parameters, different testing strategy, etc.

Would it be overkill to try and get an npm package that's used by multiple browser plugins?

**Comment by jparise** [comment]
That's not something I'm personally motivated to maintain, but if someone wanted to do that work, I'd consider using it in this project.
