### ISSUE TITLE
Remove more than just UTM tracking

### ISSUE THREAD

**Issue by JBey4you** [jparise/chrome-utm-stripper#5]
Hi!

Interesting extension you have there. Also, I found it "a little" limited. Indeed, it would be cool if we could remove other junk that appears after an URL. Here's for example : https://www.youtube.com/watch?v=WctCt-C_u1M&list=UUAHvzYK6zr9IIGayF6ZrFdQ.

Let's say you add an option to remove what we want. So here, I could put "&list=" in the settings, so I never have YouTube playlists. I did a example with YouTube, but I think you get the idea.

Would it be possible? I'm asking this because I know the addon Pure URL have this option on Firefox, but not on Chrome. So maybe, you can "fix" it (If I can say that) with your extension. Would be great I think!

**Comment by ml31415** [comment]
What about facebooks `igshid=` for instagram links? As this annoying tracking behaviour seems to become more and more popular, I suppose it makes sense to make the filtering dynamic, just like for ad blockers. Have a list of domains / parameters, and strip all of it.
