### ISSUE TITLE
Add "?_cmp" to filter list?

### ISSUE THREAD

**Issue by mattpanther** [jparise/chrome-utm-stripper#51]
Hello, any chance of adding another filter to the plugin to block trackers like in this URL? https://www.familyhandyman.com/list/temperatures-to-set-everything-in-your-home/?_cmp=diytipshintsnl&_ebid=diytipshintsnl11302021&_mid=454726&ehid=238994375794e47fa9c2730c9f08cd9106e9e6d2

**Comment by jparise** [comment]
I worry that `_cmp` is too generic of a term to always classify it as a tracking token so I don't think this is something we should add to the filter.
