### ISSUE TITLE
Remove ?mbid trackers

### ISSUE THREAD

**Issue by DerekSeaman** [jparise/chrome-utm-stripper#53]
Would be great if this plugin could remove 'mbid' trackers.

/?mbid=social_twitter&mbid=social_twitter

**Comment by jparise** [comment]
I think this one is tricky because I could see it being used as a legitimate query string parameter. Can you point me at more information that describes who/what uses `mbid` as a tracking token?

**Comment by jparise** [comment]
Closing this for now until new information is available.
