### ISSUE TITLE
Consider switching to URLSearchParams

### ISSUE THREAD

**Issue by jparise** [jparise/chrome-utm-stripper#54]
[URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) provides a standard way to manipulate query strings. That should be nicer than the raw string operations that are currently used.

**Comment by gabbsmo** [comment]
Could be a bad idea. URLSearchParams will encode query string parameters when stringifying. While this is the best practice it may break websites. One real world example is OData parameters such as $filter where according to web standards the $ should be encoded but that is invalid OData.
