### ISSUE TITLE
Remove twitter tracking tokens

### ISSUE THREAD

**Issue by mtae** [jparise/chrome-utm-stripper#56]
Any chance this extension could have a feature to remove  the t parameter in twitter links when copying and browsing?

`https://twitter.com/<username>/status/<tweet_id>?s=20&t=HR7krQlIXDozAI5NxqlHvQ`

**Comment by jparise** [comment]
Unfortunately, we don't support domain-based filtering, so unconditionally removing query string parameters named `s` and `t` would break many legitimate URLs.
