### ISSUE TITLE
Some Websites Aggressively Reload

### ISSUE THREAD

**Issue by kashev** [jparise/chrome-utm-stripper#6]
With the Tracking Token Stripper extension enabled, I visited this website:

[`https://www.buzzfeed.com/andyneuenschwander/pokemon-go-tips-and-tricks?utm_term=.du4qMQrbp#.voRVgwQn1`](https://www.buzzfeed.com/andyneuenschwander/pokemon-go-tips-and-tricks?utm_term=.du4qMQrbp#.voRVgwQn1)

And I got a redirect loop; the extension stripping the token, Buzzfeed redirecting back to the tokened URL. Not sure what the fix would be, if one is possible.

**Comment by jparise** [comment]
That's a weird one. It might be something to do with their client-side JavaScript, but I'm afraid I don't have time to dig into it right now as it appears to be Buzzfeed-specific. I'm totally open to further detail or a patch, though.

**Comment by rappo** [comment]
Just chiming in to say I'm having the same problem, same domain. After clicking a buzzfeed link utm data gets added to the URL by buzzfeed, the extension strips it, and it repeats forever. Maybe a whitelist (and adding buzzfeed to it) would be a reasonable work around?

**Comment by jparise** [comment]
@rappo I think that's a good idea, although I would define it as a blacklist. This is the first time I've seen this behavior, so it's probably not a very common issue out in the wild.

Because this will involve some options UI, it's more than I can take on at the moment, but if someone wants to give it a try and offer a PR, I'd be happy to review and merge it.

**Comment by captn3m0** [comment]
Reporting another site that does this: `https://www.washingtonpost.com/news/post-nation/wp/2016/08/12/in-texas-a-man-who-didnt-kill-anybody-is-about-to-be-executed-for-murder/?utm_term=.ba3164c5668d`

**Comment by captn3m0** [comment]
I am wondering if it would be possible to detect such a refresh loop in real-time? Without maintaining a list at all.

**Comment by jparise** [comment]
Is the leading `.` a common "thing" for these terms? Perhaps we could use that as a discriminator for these cases?

**Comment by ripsfo** [comment]
Finally realized this extension was causing the odd reload loops on washingtonpost.com and buzzfeed. Which lead me here, so I guess this is just a 'me too' comment.

**Comment by jparise** [comment]
This should now be fixed in version 2.0 (just published to the Chrome web store).
