### ISSUE TITLE
utm_id not stripped from URI; New token discovered: utm_klaviyo_id

### ISSUE THREAD

**Issue by FrancisSolomon** [jparise/chrome-utm-stripper#62]
Visited this URI today (click-through from gmail):
https://exodrones.com/?utm_id=01GRR496SNYGWVY94CN0SAK17K&utm_klaviyo_id=01FAVRZNX10YCD3M1T9PKC204T&_kx=cdL7lpDt7SFXm1vA_1gaibQfslRvQn_zDYRyUXd6YnwFl_a8f64RnE9QHHdyVREu.VDEynd
... and the **utm_id** token was not stripped. Bug? It looks like (from source) that this should have been removed. Version 2.9, running in Chrome 111.0.5563.19 (beta channel)
Also noted a new tracking token in there that I've not seen before, **utm_klaviyo_id**, that it looks like could be stripped from the URI.

**Comment by jparise** [comment]
I suspect the Gmail link problem is the same as #55.
