### ISSUE TITLE
Feature request: strip vgo_ee (ActiveCampaign)

### ISSUE THREAD

**Issue by gabbsmo** [jparise/chrome-utm-stripper#66]
Ran into this: https://www.generaxion.com/se/fordelarna-med-kanslomassig-marknadsforing/?vgo_ee=mezp%2BfGwCK1kIu35aF56PzmThFgDb4mcelKIv5zTvLu%2FKp6tPOnw%3AM3MsU6SKs2FftvmgNUq%2FVT5fzAs%2BHVpo

Some google search seem to show that the vgo_ee parameter is added by a service called ActiveCampaign.

**Comment by jparise** [comment]
Fixed by #67
