### ISSUE TITLE
Add title tag content after stripping the tokens

### ISSUE THREAD

**Issue by isotopp** [jparise/chrome-utm-stripper#7]
Additional URL transformation plugins exist that can do this, e.g.

https://chrome.google.com/webstore/detail/copy-url-%20-title/dgagjmdgbakclelfacghmmbadkdegjjh?hl=en

but having multiple plugins stacked on top of each other is slightly sucky. Add this functionality to your plugin?

**Comment by jparise** [comment]
@isotopp Could you be a bit more explicit about the behavior you'd like to see? The linked Chrome extension appears to add a clipboard affordance to the context menu, and I'm not sure how that's related to stripping URL tokens.

**Comment by jparise** [comment]
Closing due to lack of clarification. Please reopen with more details.
