### ISSUE TITLE
ICID not being stripped

### ISSUE THREAD

**Issue by Pichu0102** [jparise/chrome-utm-stripper#8]
On a url, I'm still seeing some UTM code: http://www.kshb.com/livevideo?ICID=ref_fark

**Comment by jparise** [comment]
@Pichu0102, I don't think ICID is actually a UTM code. `ICID` appears to be some other kind of tracking token.

**Comment by jparise** [comment]
Actually, this is starting to bug me too. I'll see what I can do about also stripping this tag.

**Comment by jparise** [comment]
I looked into this more, and while I'm open to stripping more parameters such as this one, I'm worried that `ICID` is a pretty generic name to remove from all potential URLs. In other words, I don't know how we can be confident it's a campaign ID and not a legitimate query string parameter.

If there's documentation somewhere (I haven't been able to find it) that says the parameter's value always starts with `ref_`, I think that might be sufficiently specific to trigger its removal. Please reopen if we can narrow down the criteria further.
